// Generated by DBC2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: acura_ilx_2016_nidec.dbc
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dbc {
    /**
        <see cref = 'RADAR_DIAGNOSTIC'/>
        <see cref = 'TRACK_0'/>
        <see cref = 'TRACK_1'/>
        <see cref = 'TRACK_10'/>
        <see cref = 'TRACK_11'/>
        <see cref = 'TRACK_12'/>
        <see cref = 'TRACK_13'/>
        <see cref = 'TRACK_14'/>
        <see cref = 'TRACK_15'/>
        <see cref = 'TRACK_2'/>
        <see cref = 'TRACK_3'/>
        <see cref = 'TRACK_4'/>
        <see cref = 'TRACK_5'/>
        <see cref = 'TRACK_6'/>
        <see cref = 'TRACK_7'/>
        <see cref = 'TRACK_8'/>
        <see cref = 'TRACK_9'/>
        <see cref = 'VEHICLE_STATE'/>
        <see cref = 'VEHICLE_STATE2'/>
        <see cref = 'XXX_101'/>
        <see cref = 'XXX_102'/>
        <see cref = 'XXX_103'/>
        <see cref = 'XXX_104'/>
        <see cref = 'XXX_105'/>
        <see cref = 'XXX_106'/>
        <see cref = 'XXX_107'/>
        <see cref = 'XXX_108'/>
        <see cref = 'XXX_109'/>
        <see cref = 'XXX_110'/>
        <see cref = 'XXX_111'/>
        <see cref = 'XXX_112'/>
        <see cref = 'XXX_113'/>
        <see cref = 'XXX_114'/>
        <see cref = 'XXX_115'/>
        <see cref = 'XXX_116'/>
        <see cref = 'XXX_117'/>
    */
    public interface acura_ilx_2016_nidec {

        // ═════════════════════════ messages ═════════════════════════

        /**
        CAN id 0x300, DLC 8, sender ADAS
        */
        class VEHICLE_STATE {
            public const uint can_id = 0x300;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "ADAS";
            [StartBit(7), BigEndian, PhysRange(0, 255)] byte SET_ME_XF9;
            [StartBit(15), BigEndian, PhysRange(0, 255), Units("kph")] byte VEHICLE_SPEED;
        }

        /**
        CAN id 0x301, DLC 8, sender ADAS
        */
        class VEHICLE_STATE2 {
            public const uint can_id = 0x301;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "ADAS";
            [MinMax(0, 268435455), StartBit(7), BigEndian, PhysRange(0, 268435455)] uint SET_ME_0F18510;
            [MinMax(0, 268435455), StartBit(27), BigEndian, PhysRange(0, 268435455)] uint SET_ME_25A0000;
        }

        /**
        CAN id 0x400, DLC 8, sender RADAR
        */
        class RADAR_DIAGNOSTIC {
            public const uint can_id = 0x400;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            need to find out more diagnostic values
            */
            [StartBit(7), BigEndian, PhysRange(0, 255), ValueTable("RADAR_DIAGNOSTIC_RADAR_STATE")] byte RADAR_STATE;
        }

        /**
        CAN id 0x410, DLC 8, sender RADAR
        */
        class XXX_101 {
            public const uint can_id = 0x410;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x411, DLC 8, sender RADAR
        */
        class XXX_102 {
            public const uint can_id = 0x411;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x412, DLC 8, sender RADAR
        */
        class XXX_103 {
            public const uint can_id = 0x412;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x413, DLC 8, sender RADAR
        */
        class XXX_104 {
            public const uint can_id = 0x413;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x414, DLC 8, sender RADAR
        */
        class XXX_105 {
            public const uint can_id = 0x414;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x415, DLC 8, sender RADAR
        */
        class XXX_106 {
            public const uint can_id = 0x415;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x416, DLC 8, sender RADAR
        */
        class XXX_107 {
            public const uint can_id = 0x416;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x417, DLC 8, sender RADAR
        */
        class XXX_108 {
            public const uint can_id = 0x417;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x420, DLC 8, sender RADAR
        */
        class XXX_109 {
            public const uint can_id = 0x420;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x421, DLC 8, sender RADAR
        */
        class XXX_110 {
            public const uint can_id = 0x421;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x422, DLC 8, sender RADAR
        */
        class XXX_111 {
            public const uint can_id = 0x422;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x423, DLC 8, sender RADAR
        */
        class XXX_112 {
            public const uint can_id = 0x423;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x424, DLC 8, sender RADAR
        */
        class XXX_113 {
            public const uint can_id = 0x424;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x430, DLC 8, sender RADAR
        */
        class TRACK_0 {
            public const uint can_id = 0x430;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x431, DLC 8, sender RADAR
        */
        class TRACK_1 {
            public const uint can_id = 0x431;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x432, DLC 8, sender RADAR
        */
        class TRACK_2 {
            public const uint can_id = 0x432;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x433, DLC 8, sender RADAR
        */
        class TRACK_3 {
            public const uint can_id = 0x433;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x434, DLC 8, sender RADAR
        */
        class TRACK_4 {
            public const uint can_id = 0x434;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x435, DLC 8, sender RADAR
        */
        class TRACK_5 {
            public const uint can_id = 0x435;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x436, DLC 8, sender RADAR
        */
        class TRACK_6 {
            public const uint can_id = 0x436;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x437, DLC 8, sender RADAR
        */
        class TRACK_7 {
            public const uint can_id = 0x437;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x438, DLC 8, sender RADAR
        */
        class TRACK_8 {
            public const uint can_id = 0x438;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x439, DLC 8, sender RADAR
        */
        class TRACK_9 {
            public const uint can_id = 0x439;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x440, DLC 8, sender RADAR
        */
        class TRACK_10 {
            public const uint can_id = 0x440;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x441, DLC 8, sender RADAR
        */
        class TRACK_11 {
            public const uint can_id = 0x441;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x442, DLC 8, sender RADAR
        */
        class TRACK_12 {
            public const uint can_id = 0x442;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x443, DLC 8, sender RADAR
        */
        class TRACK_13 {
            public const uint can_id = 0x443;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x444, DLC 8, sender RADAR
        */
        class TRACK_14 {
            public const uint can_id = 0x444;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x445, DLC 8, sender RADAR
        */
        class TRACK_15 {
            public const uint can_id = 0x445;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(0, 4095), StartBit(7), BigEndian, Factor(0.0625), PhysRange(0, 255.5), Units("m")] ushort LONG_DIST;
            [StartBit(11), BigEndian, PhysRange(0, 1)] bool NEW_TRACK;
            /**
            physical = raw * 0.0625 m
            */
            [MinMax(-512, 511), StartBit(9), BigEndian, Factor(0.0625), PhysRange(0, 63.5), Units("m")] short LAT_DIST;
            /**
            physical = raw * 0.03125 m/s
            */
            [MinMax(-2048, 2047), StartBit(31), BigEndian, Factor(0.03125), PhysRange(0, 127.5), Units("m/s")] short REL_SPEED;
        }

        /**
        CAN id 0x4FF, DLC 8, sender RADAR
        */
        class XXX_114 {
            public const uint can_id = 0x4FF;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x500, DLC 8, sender RADAR
        */
        class XXX_115 {
            public const uint can_id = 0x500;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x510, DLC 8, sender RADAR
        */
        class XXX_116 {
            public const uint can_id = 0x510;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        /**
        CAN id 0x511, DLC 8, sender RADAR
        */
        class XXX_117 {
            public const uint can_id = 0x511;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "RADAR";
        }

        // ═════════════════════════ value tables (VAL_) ═════════════════════════

        /**
        Values of RADAR_DIAGNOSTIC.RADAR_STATE
        */
        enum RADAR_DIAGNOSTIC_RADAR_STATE {
            ok = 121,
            faulted = 110,
            wrong_config = 105,
        }

        // ═════════════════════════ nodes (BU_) → hosts ═════════════════════════

        // DBC node ADAS
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct ADAS : Host { }

        // DBC node RADAR
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct RADAR : Host { }

        // DBC node NEO
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct NEO : Host { }

        // Synthetic: receives every message whose DBC receivers are unknown (Vector__XXX)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Bus : Host { }

        // ═════════════════════════ connections: one per pair of nodes that exchange messages ═════════════════════════

        interface ADAS_to_Bus : Connects<ADAS, Bus> {
            [l____________<(VEHICLE_STATE, VEHICLE_STATE2)>]
            struct Traffic { }
        }

        interface NEO_to_RADAR : Connects<NEO, RADAR> {
            [____________r<(RADAR_DIAGNOSTIC, TRACK_0, TRACK_1, TRACK_2, TRACK_3, TRACK_4, TRACK_5, TRACK_6, TRACK_7, TRACK_8, TRACK_9, TRACK_10, TRACK_11, TRACK_12, TRACK_13, TRACK_14, TRACK_15)>]
            struct Traffic { }
        }

        interface Bus_to_RADAR : Connects<Bus, RADAR> {
            [____________r<(XXX_101, XXX_102, XXX_103, XXX_104, XXX_105, XXX_106, XXX_107, XXX_108, XXX_109, XXX_110, XXX_111, XXX_112, XXX_113, XXX_114, XXX_115, XXX_116, XXX_117)>]
            struct Traffic { }
        }

        // ═════════════════════════ DBC metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field / pack.
        // They live inside the project interface (the agent expects every class in a project); the connections use
        // explicit pack lists, so they are never collected as packs.

        /** Start bit of the signal in the CAN frame, as written in the DBC (LSB for Intel, MSB for Motorola). */
        public class StartBitAttribute : Attribute { public StartBitAttribute(int bit) { } }

        /** Motorola byte order (DBC @0); absent means Intel / little-endian (@1). */
        public class BigEndianAttribute : Attribute { }

        /** Physical value = raw * factor + offset. */
        public class FactorAttribute : Attribute { public FactorAttribute(double factor) { } }

        /** Physical value = raw * factor + offset. */
        public class OffsetAttribute : Attribute { public OffsetAttribute(double offset) { } }

        /** Physical [min|max] declared in the DBC (a UI hint, not a wire constraint). */
        public class PhysRangeAttribute : Attribute { public PhysRangeAttribute(double min, double max) { } }

        /** Unit of the physical value. */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** This signal selects which multiplexed signals are present. */
        public class MultiplexorAttribute : Attribute { }

        /** Present only when the multiplexor carries this value. */
        public class MultiplexedAttribute : Attribute { public MultiplexedAttribute(long value) { } }

        /** GenSigStartValue: raw value at ECU start. */
        public class StartValueAttribute : Attribute { public StartValueAttribute(double value) { } public StartValueAttribute(string value) { } }

        /** GenMsgCycleTime: transmission period in milliseconds. */
        public class CycleTimeAttribute : Attribute { public CycleTimeAttribute(double ms) { } public CycleTimeAttribute(string ms) { } }

        /** Name of the enum listing the named raw values (used when the table does not cover the whole range). */
        public class ValueTableAttribute : Attribute { public ValueTableAttribute(string enumName) { } }

        /** Any other DBC attribute (BA_) of the message or signal. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AttrAttribute : Attribute { public AttrAttribute(string name, string value) { } }
    }
}
