// Generated by DBC2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: comma_body.dbc
// DBC VERSION "0.0.02"
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dbc {
    /**
        <see cref = 'BODY_DATA'/>
        <see cref = 'KNEE_DATA'/>
        <see cref = 'KNEE_MAX_MOTOR_RPM_CMD'/>
        <see cref = 'KNEE_MOTORS_ANGLE'/>
        <see cref = 'KNEE_MOTORS_CURRENT'/>
        <see cref = 'KNEE_MOTORS_DATA'/>
        <see cref = 'KNEE_TORQUE_CMD'/>
        <see cref = 'KNEE_VAR_VALUES'/>
        <see cref = 'MAX_MOTOR_RPM_CMD'/>
        <see cref = 'MOTORS_ANGLE'/>
        <see cref = 'MOTORS_CURRENT'/>
        <see cref = 'MOTORS_DATA'/>
        <see cref = 'TORQUE_CMD'/>
        <see cref = 'VAR_VALUES'/>
    */
    public interface comma_body {

        // ═════════════════════════ messages ═════════════════════════

        /**
        CAN id 0x201, DLC 8, sender unknown
        */
        class MOTORS_DATA {
            public const uint can_id = 0x201;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(-1000, 1000)] short SPEED_L;
            [StartBit(23), BigEndian, PhysRange(-1000, 1000)] short SPEED_R;
            [StartBit(39), BigEndian, Units("deprecated")] byte ELEC_ANGLE_L;
            [StartBit(47), BigEndian, Units("deprecated")] byte ELEC_ANGLE_R;
            [MinMax(0, 15), StartBit(51), BigEndian, PhysRange(0, 15)] byte COUNTER;
            [StartBit(63), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        /**
        CAN id 0x202, DLC 3, sender unknown
        */
        class VAR_VALUES {
            public const uint can_id = 0x202;
            public const bool extended = false;
            public const int dlc = 3;
            [StartBit(0), BigEndian, PhysRange(0, 1)] bool IGNITION;
            [StartBit(1), BigEndian, PhysRange(0, 1)] bool ENABLE_MOTORS;
            [MinMax(0, 63), StartBit(7), BigEndian, PhysRange(0, 63)] byte FAULT;
            [StartBit(15), BigEndian, PhysRange(0, 255)] byte MOTOR_ERR_L;
            [StartBit(23), BigEndian, PhysRange(0, 255)] byte MOTOR_ERR_R;
        }

        /**
        CAN id 0x203, DLC 4, sender unknown
        */
        class BODY_DATA {
            public const uint can_id = 0x203;
            public const bool extended = false;
            public const int dlc = 4;
            /**
            physical = raw * 0.1
            */
            [StartBit(7), BigEndian, Factor(0.1), PhysRange(0, 125)] byte MCU_TEMP;
            /**
            physical = raw * 0.01
            */
            [StartBit(15), BigEndian, Factor(0.01), PhysRange(0, 60)] ushort BATT_VOLTAGE;
            [MinMax(0, 127), StartBit(31), BigEndian, PhysRange(0, 100)] byte BATT_PERCENTAGE;
            [StartBit(24), BigEndian, PhysRange(0, 1)] bool CHARGER_CONNECTED;
        }

        /**
        CAN id 0x204, DLC 8, sender unknown
        */
        class MOTORS_CURRENT {
            public const uint can_id = 0x204;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(-32768, 32767)] short LEFT_PHA_AB;
            [StartBit(23), BigEndian, PhysRange(-32768, 32767)] short LEFT_PHA_BC;
            [StartBit(39), BigEndian, PhysRange(-32768, 32767)] short RIGHT_PHA_AB;
            [StartBit(55), BigEndian, PhysRange(-32768, 32767)] short RIGHT_PHA_BC;
        }

        /**
        CAN id 0x205, DLC 8, sender unknown
        */
        class MOTORS_ANGLE {
            public const uint can_id = 0x205;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(0, 16384)] ushort LEFT_ANGLE_SENSOR;
            [StartBit(23), BigEndian, PhysRange(0, 16384)] ushort RIGHT_ANGLE_SENSOR;
            [StartBit(39), BigEndian, PhysRange(0, 360)] ushort LEFT_HALL_SENSOR;
            [StartBit(55), BigEndian, PhysRange(0, 360)] ushort RIGHT_HALL_SENSOR;
        }

        /**
        CAN id 0x250, DLC 6, sender unknown
        */
        class TORQUE_CMD {
            public const uint can_id = 0x250;
            public const bool extended = false;
            public const int dlc = 6;
            [StartBit(7), BigEndian, PhysRange(-1000, 1000)] short TORQUE_L;
            [StartBit(23), BigEndian, PhysRange(-1000, 1000)] short TORQUE_R;
            [MinMax(0, 15), StartBit(35), BigEndian, PhysRange(0, 15)] byte COUNTER;
            [StartBit(47), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        /**
        CAN id 0x251, DLC 5, sender unknown
        */
        class MAX_MOTOR_RPM_CMD {
            public const uint can_id = 0x251;
            public const bool extended = false;
            public const int dlc = 5;
            [StartBit(7), BigEndian, PhysRange(0, 1000)] ushort MAX_RPM_L;
            [StartBit(23), BigEndian, PhysRange(0, 1000)] ushort MAX_RPM_R;
            [StartBit(39), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        /**
        CAN id 0x301, DLC 8, sender unknown
        */
        class KNEE_MOTORS_DATA {
            public const uint can_id = 0x301;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(-1000, 1000)] short SPEED_L;
            [StartBit(23), BigEndian, PhysRange(-1000, 1000)] short SPEED_R;
            [StartBit(39), BigEndian, Units("deprecated")] byte ELEC_ANGLE_L;
            [StartBit(47), BigEndian, Units("deprecated")] byte ELEC_ANGLE_R;
            [MinMax(0, 15), StartBit(51), BigEndian, PhysRange(0, 15)] byte COUNTER;
            [StartBit(63), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        /**
        CAN id 0x302, DLC 3, sender unknown
        */
        class KNEE_VAR_VALUES {
            public const uint can_id = 0x302;
            public const bool extended = false;
            public const int dlc = 3;
            [StartBit(0), BigEndian, PhysRange(0, 1)] bool IGNITION;
            [StartBit(1), BigEndian, PhysRange(0, 1)] bool ENABLE_MOTORS;
            [MinMax(0, 63), StartBit(7), BigEndian, PhysRange(0, 63)] byte FAULT;
            [StartBit(15), BigEndian, PhysRange(0, 255)] byte MOTOR_ERR_L;
            [StartBit(23), BigEndian, PhysRange(0, 255)] byte MOTOR_ERR_R;
        }

        /**
        CAN id 0x303, DLC 4, sender unknown
        */
        class KNEE_DATA {
            public const uint can_id = 0x303;
            public const bool extended = false;
            public const int dlc = 4;
            /**
            physical = raw * 0.1
            */
            [StartBit(7), BigEndian, Factor(0.1), PhysRange(0, 125)] byte MCU_TEMP;
            /**
            physical = raw * 0.01
            */
            [StartBit(15), BigEndian, Factor(0.01), PhysRange(0, 60)] ushort BATT_VOLTAGE;
            [MinMax(0, 127), StartBit(31), BigEndian, PhysRange(0, 100)] byte BATT_PERCENTAGE;
            [StartBit(24), BigEndian, PhysRange(0, 1)] bool CHARGER_CONNECTED;
        }

        /**
        CAN id 0x304, DLC 8, sender unknown
        */
        class KNEE_MOTORS_CURRENT {
            public const uint can_id = 0x304;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(-32768, 32767)] short LEFT_PHA_AB;
            [StartBit(23), BigEndian, PhysRange(-32768, 32767)] short LEFT_PHA_BC;
            [StartBit(39), BigEndian, PhysRange(-32768, 32767)] short RIGHT_PHA_AB;
            [StartBit(55), BigEndian, PhysRange(-32768, 32767)] short RIGHT_PHA_BC;
        }

        /**
        CAN id 0x305, DLC 8, sender unknown
        */
        class KNEE_MOTORS_ANGLE {
            public const uint can_id = 0x305;
            public const bool extended = false;
            public const int dlc = 8;
            [StartBit(7), BigEndian, PhysRange(0, 16384)] ushort LEFT_ANGLE_SENSOR;
            [StartBit(23), BigEndian, PhysRange(0, 16384)] ushort RIGHT_ANGLE_SENSOR;
            [StartBit(39), BigEndian, PhysRange(0, 360)] ushort LEFT_HALL_SENSOR;
            [StartBit(55), BigEndian, PhysRange(0, 360)] ushort RIGHT_HALL_SENSOR;
        }

        /**
        CAN id 0x350, DLC 6, sender unknown
        */
        class KNEE_TORQUE_CMD {
            public const uint can_id = 0x350;
            public const bool extended = false;
            public const int dlc = 6;
            [StartBit(7), BigEndian, PhysRange(-1000, 1000)] short TORQUE_L;
            [StartBit(23), BigEndian, PhysRange(-1000, 1000)] short TORQUE_R;
            [MinMax(0, 15), StartBit(35), BigEndian, PhysRange(0, 15)] byte COUNTER;
            [StartBit(47), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        /**
        CAN id 0x351, DLC 5, sender unknown
        */
        class KNEE_MAX_MOTOR_RPM_CMD {
            public const uint can_id = 0x351;
            public const bool extended = false;
            public const int dlc = 5;
            [StartBit(7), BigEndian, PhysRange(0, 1000)] ushort MAX_RPM_L;
            [StartBit(23), BigEndian, PhysRange(0, 1000)] ushort MAX_RPM_R;
            [StartBit(39), BigEndian, PhysRange(0, 255)] byte CHECKSUM;
        }

        // ═════════════════════════ nodes (BU_) → hosts ═════════════════════════

        // Synthetic: receives every message whose DBC receivers are unknown (Vector__XXX)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Bus : Host { }

        // Synthetic: sends every message whose DBC sender is unknown (Vector__XXX)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct UnknownECU : Host { }

        // ═════════════════════════ connections: one per pair of nodes that exchange messages ═════════════════════════

        interface Bus_to_UnknownECU : Connects<Bus, UnknownECU> {
            [____________r<(MOTORS_DATA, VAR_VALUES, BODY_DATA, MOTORS_CURRENT, MOTORS_ANGLE, TORQUE_CMD, MAX_MOTOR_RPM_CMD, KNEE_MOTORS_DATA, KNEE_VAR_VALUES, KNEE_DATA, KNEE_MOTORS_CURRENT, KNEE_MOTORS_ANGLE, KNEE_TORQUE_CMD, KNEE_MAX_MOTOR_RPM_CMD)>]
            struct Traffic { }
        }

        // ═════════════════════════ DBC metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field / pack.
        // They live inside the project interface (the agent expects every class in a project); the connections use
        // explicit pack lists, so they are never collected as packs.

        /** Start bit of the signal in the CAN frame, as written in the DBC (LSB for Intel, MSB for Motorola). */
        public class StartBitAttribute : Attribute { public StartBitAttribute(int bit) { } }

        /** Motorola byte order (DBC @0); absent means Intel / little-endian (@1). */
        public class BigEndianAttribute : Attribute { }

        /** Physical value = raw * factor + offset. */
        public class FactorAttribute : Attribute { public FactorAttribute(double factor) { } }

        /** Physical value = raw * factor + offset. */
        public class OffsetAttribute : Attribute { public OffsetAttribute(double offset) { } }

        /** Physical [min|max] declared in the DBC (a UI hint, not a wire constraint). */
        public class PhysRangeAttribute : Attribute { public PhysRangeAttribute(double min, double max) { } }

        /** Unit of the physical value. */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** This signal selects which multiplexed signals are present. */
        public class MultiplexorAttribute : Attribute { }

        /** Present only when the multiplexor carries this value. */
        public class MultiplexedAttribute : Attribute { public MultiplexedAttribute(long value) { } }

        /** GenSigStartValue: raw value at ECU start. */
        public class StartValueAttribute : Attribute { public StartValueAttribute(double value) { } public StartValueAttribute(string value) { } }

        /** GenMsgCycleTime: transmission period in milliseconds. */
        public class CycleTimeAttribute : Attribute { public CycleTimeAttribute(double ms) { } public CycleTimeAttribute(string ms) { } }

        /** Name of the enum listing the named raw values (used when the table does not cover the whole range). */
        public class ValueTableAttribute : Attribute { public ValueTableAttribute(string enumName) { } }

        /** Any other DBC attribute (BA_) of the message or signal. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AttrAttribute : Attribute { public AttrAttribute(string name, string value) { } }
    }
}
