// Generated by DBC2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: gm_global_a_chassis.dbc
//          https://github.com/commaai/opendbc/blob/master/opendbc/dbc/gm_global_a_chassis.dbc
// DBC attribute UseGMParameterIDs = 0
// DBC attribute BusType = CAN
// DBC attribute ProtocolType = GMLAN
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.dbc {
    /**
        <see cref = 'EBCMFrictionBrakeCmd'/>
        <see cref = 'EBCMFrictionBrakeStatus'/>
        <see cref = 'EBCMRegen'/>
        <see cref = 'PACMParkAssitCmd'/>
    */
    public interface gm_global_a_chassis {

        // ═════════════════════════ messages ═════════════════════════

        /**
        CAN id 0x337, DLC 7, sender NEO
        */
        class PACMParkAssitCmd {
            public const uint can_id = 0x337;
            public const bool extended = false;
            public const int dlc = 7;
            public const string sender = "NEO";
            [MinMax(0, 3), StartBit(35), BigEndian] byte RollingCounter;
            [StartBit(47), BigEndian] ushort SteeringWheelChecksum;
            [StartBit(23), BigEndian] ushort SteeringWheelCmd;
        }

        /**
        CAN id 0x230, DLC 6, sender K17_EBCM
        */
        class EBCMRegen {
            public const uint can_id = 0x230;
            public const bool extended = false;
            public const int dlc = 6;
            public const string sender = "K17_EBCM";
            [MinMax(0, 1023), StartBit(1), BigEndian] ushort Regen;
        }

        /**
        CAN id 0x170, DLC 8, sender K17_EBCM
        */
        class EBCMFrictionBrakeStatus {
            public const uint can_id = 0x170;
            public const bool extended = false;
            public const int dlc = 8;
            public const string sender = "K17_EBCM";
            [StartBit(23), BigEndian] ushort FrictionBrakePressure;
        }

        /**
        CAN id 0x315, DLC 5, sender K17_EBCM
        */
        class EBCMFrictionBrakeCmd {
            public const uint can_id = 0x315;
            public const bool extended = false;
            public const int dlc = 5;
            public const string sender = "K17_EBCM";
            [MinMax(0, 3), StartBit(33), BigEndian] byte RollingCounter;
            [MinMax(0, 15), StartBit(7), BigEndian] byte FrictionBrakeMode;
            [StartBit(23), BigEndian] ushort FrictionBrakeChecksum;
            [MinMax(-2048, 2047), StartBit(3), BigEndian] short FrictionBrakeCmd;
        }

        // ═════════════════════════ nodes (BU_) → hosts ═════════════════════════

        // DBC node K182_PACM: Parking Assist Control Module
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct K182_PACM : Host { }

        // DBC node K43_PSCM: Power Steering Control Module
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct K43_PSCM : Host { }

        // DBC node K17_EBCM: Electronic Brake Control Module
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct K17_EBCM : Host { }

        // DBC node NEO: Comma NEO
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct NEO : Host { }

        // DBC node K124_ASCM: Active Safety Control Module
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct K124_ASCM : Host { }

        // Synthetic: receives every message whose DBC receivers are unknown (Vector__XXX)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Bus : Host { }

        // ═════════════════════════ connections: one per pair of nodes that exchange messages ═════════════════════════

        interface Bus_to_NEO : Connects<Bus, NEO> {
            [____________r<PACMParkAssitCmd>]
            struct Traffic { }
        }

        interface K17_EBCM_to_NEO : Connects<K17_EBCM, NEO> {
            [l____________<(EBCMRegen, EBCMFrictionBrakeStatus, EBCMFrictionBrakeCmd)>]
            struct Traffic { }
        }

        // ═════════════════════════ DBC metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field / pack.
        // They live at the end of the project interface, where the AdHoc manual collects attribute declarations; the connections use
        // explicit pack lists, so they are never collected as packs.

        /** Start bit of the signal in the CAN frame, as written in the DBC (LSB for Intel, MSB for Motorola). */
        public class StartBitAttribute : Attribute { public StartBitAttribute(int bit) { } }

        /** Motorola byte order (DBC @0); absent means Intel / little-endian (@1). */
        public class BigEndianAttribute : Attribute { }

        /** Physical value = raw * factor + offset. */
        public class FactorAttribute : Attribute { public FactorAttribute(double factor) { } }

        /** Physical value = raw * factor + offset. */
        public class OffsetAttribute : Attribute { public OffsetAttribute(double offset) { } }

        /** Physical [min|max] declared in the DBC (a UI hint, not a wire constraint). */
        public class PhysRangeAttribute : Attribute { public PhysRangeAttribute(double min, double max) { } }

        /** Unit of the physical value. */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** This signal selects which multiplexed signals are present. */
        public class MultiplexorAttribute : Attribute { }

        /** Present only when the multiplexor carries this value. */
        public class MultiplexedAttribute : Attribute { public MultiplexedAttribute(long value) { } }

        /** GenSigStartValue: raw value at ECU start. */
        public class StartValueAttribute : Attribute { public StartValueAttribute(double value) { } public StartValueAttribute(string value) { } }

        /** GenMsgCycleTime: transmission period in milliseconds. */
        public class CycleTimeAttribute : Attribute { public CycleTimeAttribute(double ms) { } public CycleTimeAttribute(string ms) { } }

        /** Name of the enum listing the named raw values (used when the table does not cover the whole range). */
        public class ValueTableAttribute : Attribute { public ValueTableAttribute(string enumName) { } }

        /** Any other DBC attribute (BA_) of the message or signal. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AttrAttribute : Attribute { public AttrAttribute(string name, string value) { } }
    }
}
